/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HouseholdsIndexRouteImport } from './routes/households/index'
import { Route as HouseholdsIdRouteImport } from './routes/households/$id'
import { Route as HouseholdsNewRouteImport } from './routes/households/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsIndexRoute = HouseholdsIndexRouteImport.update({
  id: '/households/',
  path: '/households/',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsIdRoute = HouseholdsIdRouteImport.update({
  id: '/households/$id',
  path: '/households/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsNewRoute = HouseholdsNewRouteImport.update({
  id: '/households/new',
  path: '/households/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/locations': typeof LocationsRoute
  '/settings': typeof SettingsRoute
  '/households/$id': typeof HouseholdsIdRoute
  '/households/new': typeof HouseholdsNewRoute
  '/households/': typeof HouseholdsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/locations': typeof LocationsRoute
  '/settings': typeof SettingsRoute
  '/households/$id': typeof HouseholdsIdRoute
  '/households/new': typeof HouseholdsNewRoute
  '/households': typeof HouseholdsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/locations': typeof LocationsRoute
  '/settings': typeof SettingsRoute
  '/households/$id': typeof HouseholdsIdRoute
  '/households/new': typeof HouseholdsNewRoute
  '/households/': typeof HouseholdsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/locations'
    | '/settings'
    | '/households/$id'
    | '/households/new'
    | '/households/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/locations'
    | '/settings'
    | '/households/$id'
    | '/households/new'
    | '/households'
  id:
    | '__root__'
    | '/'
    | '/locations'
    | '/settings'
    | '/households/$id'
    | '/households/new'
    | '/households/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocationsRoute: typeof LocationsRoute
  SettingsRoute: typeof SettingsRoute
  HouseholdsIdRoute: typeof HouseholdsIdRoute
  HouseholdsNewRoute: typeof HouseholdsNewRoute
  HouseholdsIndexRoute: typeof HouseholdsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households/': {
      id: '/households/'
      path: '/households'
      fullPath: '/households/'
      preLoaderRoute: typeof HouseholdsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households/$id': {
      id: '/households/$id'
      path: '/households/$id'
      fullPath: '/households/$id'
      preLoaderRoute: typeof HouseholdsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households/new': {
      id: '/households/new'
      path: '/households/new'
      fullPath: '/households/new'
      preLoaderRoute: typeof HouseholdsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocationsRoute: LocationsRoute,
  SettingsRoute: SettingsRoute,
  HouseholdsIdRoute: HouseholdsIdRoute,
  HouseholdsNewRoute: HouseholdsNewRoute,
  HouseholdsIndexRoute: HouseholdsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
